services:
  checkmk:
    image: checkmk/check-mk-raw:latest
    container_name: checkmk
    restart: always
    ports:
      - "5000:5000"
      - "6556:6556"
      - "161:161/udp"
      - "162:162/udp"
    volumes:
      - ./data:/omd/sites
    environment:
      - CMK_SITE_ID=%name%
      - CMK_PASSWORD=%password%
